# Generated by Django 5.1.2 on 2024-10-26 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_file_embedding_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='embedding_index',
        ),
        migrations.RemoveField(
            model_name='file',
            name='embedding',
        ),
    ]
