# Generated by Django 5.1.2 on 2024-10-26 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
